In [1]:
import pandas as pd
import numpy as np
from regression_inference import OrdinalLogisticRegression, summary
from statsmodels.miscmodels.ordinal_model import OrderedModel
import statsmodels.api as sm

In [2]:
anes_data = sm.datasets.anes96.load()
anes_exog = anes_data.exog

X=pd.DataFrame(anes_exog)
y=pd.Series(anes_data.endog)

In [3]:
mod = OrderedModel(y, X, distr='logit')
res = mod.fit(method="bfgs")
print(res.summary())

Optimization terminated successfully.
         Current function value: 1.583283
         Iterations: 35
         Function evaluations: 37
         Gradient evaluations: 37
                             OrderedModel Results                             
Dep. Variable:                    PID   Log-Likelihood:                -1494.6
Model:                   OrderedModel   AIC:                             3011.
Method:            Maximum Likelihood   BIC:                             3065.
Date:                Sat, 13 Dec 2025                                         
Time:                        19:11:19                                         
No. Observations:                 944                                         
Df Residuals:                     933                                         
Df Model:                           5                                         
                 coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------

In [4]:
model_ord = OrdinalLogisticRegression().fit(X, y)
model_ord

/tmp/ipykernel_147496/3225600301.py:1: UserWarning: 
Optimization did not converge after 100 iterations.
Optimizer message: Desired error not necessarily achieved due to precision loss.
Consider:
- Increasing max_iter
- Adjusting tolerance
- Scaling features
- Checking for separation issues
- Ensuring sufficient samples per class

  model_ord = OrdinalLogisticRegression().fit(X, y)


OrdinalLogisticRegression(feature_names=Index(['logpopul', 'selfLR', 'age', 'educ', 'income'], dtype='object'), target='PID', alpha=0.05, theta=array([-0.07073006,  1.01917591, -0.0041626 ,  0.1776701 ,  0.04718544,
        3.68910138,  0.22433654, -0.34450995, -1.35646674, -0.42465778,
        0.16531176]), coefficients=array([-0.07073006,  1.01917591, -0.0041626 ,  0.1776701 ,  0.04718544]), intercept=None, predictions=array([6, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 5, 0, 0, 5, 0, 0, 0,
       0, 6, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 6, 0, 0, 6, 6, 0, 1, 5, 0, 6,
       1, 6, 1, 0, 0, 0, 1, 5, 0, 1, 0, 5, 1, 0, 6, 0, 0, 0, 0, 0, 0, 0,
       6, 6, 6, 5, 1, 0, 5, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 6, 0, 5, 5,
       0, 0, 0, 1, 6, 5, 5, 0, 1, 0, 5, 1, 1, 6, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 5, 6, 5, 6, 6, 1, 0, 1, 1, 0, 0, 6, 5, 0, 0, 0, 6, 1, 0, 0,
       6, 6, 0, 5, 1, 0, 0, 5, 0, 6, 1, 5, 5, 6, 0, 0, 0, 1, 6, 0, 0, 1,
       1, 0, 1, 5, 1, 1, 1, 1, 1, 1, 1, 0, 6, 0, 5, 1, 1, 6, 5, 

In [5]:
model_ord.variance_coefficient

array([[ 3.13893751e-04,  1.01299190e-05,  3.04133959e-06,
         9.37948381e-06,  1.26758651e-05,  1.32564289e-03,
         1.25199215e-03,  1.20741340e-03,  1.20187340e-03,
         1.12860079e-03,  1.11600950e-03],
       [ 1.01299190e-05,  2.46748087e-03, -6.05261193e-06,
         3.71133205e-04,  9.67234815e-06,  1.03981831e-02,
         1.14744779e-02,  1.19617670e-02,  1.23596768e-02,
         1.34354056e-02,  1.42122530e-02],
       [ 3.04133959e-06, -6.05261193e-06,  1.23987952e-05,
         2.14706235e-05,  1.36718870e-06,  6.85178127e-04,
         6.84271414e-04,  6.84352088e-04,  6.84428266e-04,
         6.93036053e-04,  6.72996948e-04],
       [ 9.37948381e-06,  3.71133205e-04,  2.14706235e-05,
         1.45789848e-03, -1.26423481e-04,  6.94303207e-03,
         7.11737968e-03,  7.14826155e-03,  7.30743298e-03,
         7.51906660e-03,  7.59522320e-03],
       [ 1.26758651e-05,  9.67234815e-06,  1.36718870e-06,
        -1.26423481e-04,  1.01130836e-04,  1.13707604e-03,
  

In [6]:
model_ord.aic

np.float64(3011.2390139567674)

In [7]:
model_ord.bic

np.float64(3064.5904017843677)

In [8]:
model_ord.log_likelihood

np.float64(-1494.6195069783837)

In [9]:
model_ord.null_log_likelihood

np.float64(-1750.3467099898219)

In [18]:
model_ord.theta

array([-0.07073006,  1.01917591, -0.0041626 ,  0.1776701 ,  0.04718544,
        3.68910138,  0.22433654, -0.34450995, -1.35646674, -0.42465778,
        0.16531176])

In [11]:
model_ord.coefficients

array([-0.07073006,  1.01917591, -0.0041626 ,  0.1776701 ,  0.04718544])

In [12]:
model_ord.alpha_cutpoints

array([3.68910138, 4.9405935 , 5.649161  , 5.90673023, 6.56072379,
       7.74048465])

In [13]:
model_ord.std_error_coefficient

array([0.01771705, 0.04967374, 0.00352119, 0.03818244, 0.01005638,
       0.35927582, 0.37272631, 0.37885301, 0.38547346, 0.40408886,
       0.41412832])

In [14]:
model_ord.z_stat_coefficient

array([-3.99220381, 20.51739659, -1.18215672,  4.65318904,  4.69208842,
       10.26815928, 13.25528494, 14.91122104, 15.32331234, 16.23584442,
       18.6910293 ])

In [15]:
model_ord.p_value_coefficient

array([6.54620707e-05, 0.00000000e+00, 2.37143523e-01, 3.26840342e-06,
       2.70430202e-06, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00])

In [16]:
model_ord.ci_low

array([-0.10545484,  0.92181716, -0.01106401,  0.1028339 ,  0.02747529,
        2.98493371,  4.21006335,  4.90662274,  5.15121613,  5.76872419,
        6.92880805])

In [17]:
model_ord.ci_high

array([-3.60052884e-02,  1.11653466e+00,  2.73880896e-03,  2.52506297e-01,
        6.68955858e-02,  4.39326905e+00,  5.67112366e+00,  6.39169926e+00,
        6.66224433e+00,  7.35272339e+00,  8.55216125e+00])